import Head from "next/head";
import Dashboard from "./dashboard";
import SideMenu from "@/components/SideMenu";
import { useSession } from "next-auth/react"
import Login from "@/components/login";
import classes from './Home.module.scss'
import React from 'react';

const Home: React.FC = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Data Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${classes.main}`}>
        { session ?
          <>
            <SideMenu />
            <Dashboard />
          </> :
          <Login />
        }
      </main>
    </>
  );
}

export default Home;